[sdl]
autolock=false
fullscreen=false

[dosbox]
title=三国志英杰传
memsize=16
machine=svga_s3

[render]
frameskip=0
aspect=true
scaler=normal2x

[cpu]
core=auto
cputype=auto
cycles=8000
cycleup=1000
cycledown=1000

[mixer]
nosound=false
rate=22050
blocksize=1024
prebuffer=20

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default
oplrate=22050

[gus]
gus=false

[speaker]
pcspeaker=true
pcrate=22050
tandy=auto
tandyrate=22050
disney=false

[dos]
xms=true
ems=true
umb=true

[autoexec]
@echo off
mount c .
c:
REKO3.COM
